# Generated by Django 5.0.7 on 2024-10-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepost',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
