# Generated by Django 5.0.7 on 2024-10-21 14:37

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_gamepost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 18)),
        ),
    ]
