# Generated by Django 5.0.7 on 2024-10-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_gamepost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='date',
            field=models.DateField(default='2024-11-18'),
        ),
    ]
