# Generated by Django 5.0.7 on 2024-10-21 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_gamepost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 18)),
        ),
    ]
