# Generated by Django 5.0.7 on 2024-10-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_gamepost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='img_update',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
