# Generated by Django 5.0.7 on 2024-10-22 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'коментарий', 'verbose_name_plural': 'коментарии'},
        ),
        migrations.AddField(
            model_name='comments',
            name='belonging',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='post.gamepost', verbose_name='Принадлежность'),
            preserve_default=False,
        ),
    ]
